"""Add fields to GeneratedReport

Revision ID: 14b1be682e17
Revises: 767292c227d2
Create Date: 2026-07-25 14:41:26.266994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b1be682e17'
down_revision: Union[str, None] = '767292c227d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_reports', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('generated_reports', sa.Column('report_date', sa.String(length=50), nullable=True))
    op.add_column('generated_reports', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('generated_reports', sa.Column('pdf_path', sa.String(length=500), nullable=True))
    op.add_column('generated_reports', sa.Column('html_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_reports', 'html_path')
    op.drop_column('generated_reports', 'pdf_path')
    op.drop_column('generated_reports', 'version')
    op.drop_column('generated_reports', 'report_date')
    op.drop_column('generated_reports', 'status')
    # ### end Alembic commands ###
