"""Add research schema fields for M5

Revision ID: 767292c227d2
Revises: 9c92b537ee30
Create Date: 2026-07-25 13:28:17.298256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767292c227d2'
down_revision: Union[str, None] = '9c92b537ee30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('research_chunks', sa.Column('section', sa.String(length=200), nullable=True))
    op.add_column('research_documents', sa.Column('document_type', sa.String(length=100), nullable=True))
    op.add_column('research_documents', sa.Column('original_url', sa.String(length=1000), nullable=True))
    op.add_column('research_documents', sa.Column('document_identifier', sa.String(length=100), nullable=True))
    op.drop_constraint('research_documents_pdf_url_key', 'research_documents', type_='unique')
    op.create_unique_constraint(None, 'research_documents', ['original_url'])
    op.create_unique_constraint(None, 'research_documents', ['document_identifier'])
    op.drop_column('research_documents', 'pdf_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_documents', sa.Column('pdf_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'research_documents', type_='unique')
    op.drop_constraint(None, 'research_documents', type_='unique')
    op.create_unique_constraint('research_documents_pdf_url_key', 'research_documents', ['pdf_url'])
    op.drop_column('research_documents', 'document_identifier')
    op.drop_column('research_documents', 'original_url')
    op.drop_column('research_documents', 'document_type')
    op.drop_column('research_chunks', 'section')
    op.drop_column('research_chunks', 'page_number')
    # ### end Alembic commands ###
