"""Initial Schema

Revision ID: 9c92b537ee30
Revises: 
Create Date: 2026-07-25 12:45:13.334666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c92b537ee30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_runs',
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_runs_id'), 'ai_analysis_runs', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('related_entity_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=True)
    op.create_table('economic_indicators',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_indicators_code'), 'economic_indicators', ['code'], unique=True)
    op.create_index(op.f('ix_economic_indicators_id'), 'economic_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_economic_indicators_name'), 'economic_indicators', ['name'], unique=True)
    op.create_table('emerging_problems',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emerging_problems_id'), 'emerging_problems', ['id'], unique=False)
    op.create_table('research_documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.String(length=500), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pdf_url')
    )
    op.create_index(op.f('ix_research_documents_id'), 'research_documents', ['id'], unique=False)
    op.create_index(op.f('ix_research_documents_title'), 'research_documents', ['title'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('data_source_configs',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('parsing_rules', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_configs_id'), 'data_source_configs', ['id'], unique=False)
    op.create_table('detected_trends',
    sa.Column('indicator_id', sa.UUID(), nullable=False),
    sa.Column('trend_direction', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=False),
    sa.Column('pct_change', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('detection_method', sa.String(length=100), nullable=False),
    sa.Column('supporting_observations', sa.Text(), nullable=True),
    sa.Column('source_references', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['economic_indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_trends_id'), 'detected_trends', ['id'], unique=False)
    op.create_index(op.f('ix_detected_trends_indicator_id'), 'detected_trends', ['indicator_id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_reports_id'), 'generated_reports', ['id'], unique=False)
    op.create_table('indicator_metadata',
    sa.Column('indicator_id', sa.UUID(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('source_agency', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['economic_indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_id')
    )
    op.create_index(op.f('ix_indicator_metadata_id'), 'indicator_metadata', ['id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cron_schedule', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_table('news_articles',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_source_id'), 'news_articles', ['source_id'], unique=False)
    op.create_table('policy_targets',
    sa.Column('indicator_id', sa.UUID(), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('target_unit', sa.String(length=50), nullable=False),
    sa.Column('target_period', sa.String(length=100), nullable=False),
    sa.Column('target_source', sa.String(length=255), nullable=False),
    sa.Column('target_document', sa.String(length=1000), nullable=True),
    sa.Column('responsible_institution', sa.String(length=255), nullable=True),
    sa.Column('methodology', sa.String(length=2000), nullable=True),
    sa.Column('source_citation', sa.String(length=1000), nullable=True),
    sa.Column('higher_is_better', sa.Boolean(), nullable=False),
    sa.Column('importance_weight', sa.Float(), nullable=False),
    sa.Column('target_confidence', sa.Float(), nullable=False),
    sa.Column('neutral_tolerance_percent', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['economic_indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_targets_id'), 'policy_targets', ['id'], unique=False)
    op.create_index(op.f('ix_policy_targets_indicator_id'), 'policy_targets', ['indicator_id'], unique=False)
    op.create_table('problem_evidence',
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['emerging_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_evidence_id'), 'problem_evidence', ['id'], unique=False)
    op.create_table('raw_data_records',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_data_records_id'), 'raw_data_records', ['id'], unique=False)
    op.create_index(op.f('ix_raw_data_records_is_processed'), 'raw_data_records', ['is_processed'], unique=False)
    op.create_table('research_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['research_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qdrant_point_id')
    )
    op.create_index(op.f('ix_research_chunks_id'), 'research_chunks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('indicator_observations',
    sa.Column('indicator_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['economic_indicators.id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_data_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_observations_id'), 'indicator_observations', ['id'], unique=False)
    op.create_index(op.f('ix_indicator_observations_indicator_id'), 'indicator_observations', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_indicator_observations_timestamp'), 'indicator_observations', ['timestamp'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_id'), 'ingestion_runs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('news_topics',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('topic_label', sa.String(length=200), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_model_version', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_topics_id'), 'news_topics', ['id'], unique=False)
    op.create_index(op.f('ix_news_topics_topic_label'), 'news_topics', ['topic_label'], unique=False)
    op.create_table('policy_actuals',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('actual_period', sa.String(length=100), nullable=False),
    sa.Column('actual_source', sa.String(length=255), nullable=False),
    sa.Column('data_quality_status', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['policy_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_actuals_id'), 'policy_actuals', ['id'], unique=False)
    op.create_table('report_citations',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('citation_text', sa.String(length=500), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['generated_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_citations_id'), 'report_citations', ['id'], unique=False)
    op.create_table('research_citations',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('context_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['research_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_citations_id'), 'research_citations', ['id'], unique=False)
    op.create_table('sentiment_analysis_results',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('ai_model_version', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index(op.f('ix_sentiment_analysis_results_id'), 'sentiment_analysis_results', ['id'], unique=False)
    op.create_table('detected_anomalies',
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('algorithm_used', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['indicator_observations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id')
    )
    op.create_index(op.f('ix_detected_anomalies_id'), 'detected_anomalies', ['id'], unique=False)
    op.create_table('policy_gaps',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('actual_id', sa.UUID(), nullable=False),
    sa.Column('gap_value', sa.Float(), nullable=False),
    sa.Column('gap_percentage', sa.Float(), nullable=False),
    sa.Column('gap_status', sa.String(length=50), nullable=False),
    sa.Column('engine_score', sa.Float(), nullable=False),
    sa.Column('magnitude_score', sa.Float(), nullable=False),
    sa.Column('persistence_score', sa.Float(), nullable=False),
    sa.Column('analysis_notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actual_id'], ['policy_actuals.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['policy_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_gaps_id'), 'policy_gaps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_gaps_id'), table_name='policy_gaps')
    op.drop_table('policy_gaps')
    op.drop_index(op.f('ix_detected_anomalies_id'), table_name='detected_anomalies')
    op.drop_table('detected_anomalies')
    op.drop_index(op.f('ix_sentiment_analysis_results_id'), table_name='sentiment_analysis_results')
    op.drop_table('sentiment_analysis_results')
    op.drop_index(op.f('ix_research_citations_id'), table_name='research_citations')
    op.drop_table('research_citations')
    op.drop_index(op.f('ix_report_citations_id'), table_name='report_citations')
    op.drop_table('report_citations')
    op.drop_index(op.f('ix_policy_actuals_id'), table_name='policy_actuals')
    op.drop_table('policy_actuals')
    op.drop_index(op.f('ix_news_topics_topic_label'), table_name='news_topics')
    op.drop_index(op.f('ix_news_topics_id'), table_name='news_topics')
    op.drop_table('news_topics')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_indicator_observations_timestamp'), table_name='indicator_observations')
    op.drop_index(op.f('ix_indicator_observations_indicator_id'), table_name='indicator_observations')
    op.drop_index(op.f('ix_indicator_observations_id'), table_name='indicator_observations')
    op.drop_table('indicator_observations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_research_chunks_id'), table_name='research_chunks')
    op.drop_table('research_chunks')
    op.drop_index(op.f('ix_raw_data_records_is_processed'), table_name='raw_data_records')
    op.drop_index(op.f('ix_raw_data_records_id'), table_name='raw_data_records')
    op.drop_table('raw_data_records')
    op.drop_index(op.f('ix_problem_evidence_id'), table_name='problem_evidence')
    op.drop_table('problem_evidence')
    op.drop_index(op.f('ix_policy_targets_indicator_id'), table_name='policy_targets')
    op.drop_index(op.f('ix_policy_targets_id'), table_name='policy_targets')
    op.drop_table('policy_targets')
    op.drop_index(op.f('ix_news_articles_source_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_indicator_metadata_id'), table_name='indicator_metadata')
    op.drop_table('indicator_metadata')
    op.drop_index(op.f('ix_generated_reports_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_detected_trends_indicator_id'), table_name='detected_trends')
    op.drop_index(op.f('ix_detected_trends_id'), table_name='detected_trends')
    op.drop_table('detected_trends')
    op.drop_index(op.f('ix_data_source_configs_id'), table_name='data_source_configs')
    op.drop_table('data_source_configs')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_research_documents_title'), table_name='research_documents')
    op.drop_index(op.f('ix_research_documents_id'), table_name='research_documents')
    op.drop_table('research_documents')
    op.drop_index(op.f('ix_emerging_problems_id'), table_name='emerging_problems')
    op.drop_table('emerging_problems')
    op.drop_index(op.f('ix_economic_indicators_name'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_id'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_code'), table_name='economic_indicators')
    op.drop_table('economic_indicators')
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_ai_analysis_runs_id'), table_name='ai_analysis_runs')
    op.drop_table('ai_analysis_runs')
    # ### end Alembic commands ###
